### ISSUE TITLE
"Color" CSS property

### ISSUE THREAD

**Issue by MaximShishov** [diy/jquery-placeholder#16]
In my project I had to add COLOR property to the list. I think this property will be useful and should be added to the code (IMHO).

**Comment by brianreavis** [comment]
Thanks for the suggestion! The problem with this is that "color" represents the color of the actual input text, instead of the lighter placeholder text. If there were a good way to detect the color applied to the placeholder (inherited from CSS), that'd be ideal... but there isn't a way to do that, as far as I know. Also, setting the placeholder color explicitly within the plugin would require `!important` flags in CSS to override it, which I'd prefer not.
